name: Docker Image CI

on:
  workflow_call:
    inputs:
      docker-dir:
        description: 'Directory of the Dockerfile to build (no trailing slash please)'
        required: true
        type: string
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./hugobuilder --file  ./hugobuilder/Dockerfile --tag test:$(date +%s)
